#!/bin/bash

# ------------------------------------------------------------------------------
#
# F5 BIG-IP to Zabbix Template Converter
#
# Version:  1.1
# Date:     August 2017
# Author:   Vladimir Akhmarov
#
# Description:
#   This script is a converter from F5 BIG-IP MIB files to Zabbix Template files
#   Use command "snmptranslate -Tp -m F5-BIGIP-SYSTEM-MIB 1.3.6.1.4.1.3375" to
#   walk over F5 Network OID tree
#
# ------------------------------------------------------------------------------

MIB_DIR="${HOME}/.snmp/mibs"
MIB_F5NET="mibs_netsnmp.tar.gz"
MIB_F5PRIV="mibs_f5.tar.gz"

M2Z_BIN="./mib2zabbix.pl"
M2Z_URL="https://raw.githubusercontent.com/cavaliercoder/mib2zabbix/master/mib2zabbix.pl"

T1_MIB_NAME="F5-BIGIP-SYSTEM-MIB"
T1_BASE_OID="1.3.6.1.4.1.3375.2.1"
T1_TPL_NAME="Template SNMP F5 BIG-IP - System"

T2_MIB_NAME="F5-BIGIP-LOCAL-MIB"
T2_BASE_OID="1.3.6.1.4.1.3375.2.2"
T2_TPL_NAME="Template SNMP F5 BIG-IP - LTM"

T3_MIB_NAME="F5-BIGIP-GLOBAL-MIB"
T3_BASE_OID="1.3.6.1.4.1.3375.2.3"
T3_TPL_NAME="Template SNMP F5 BIG-IP - GTM"

T4_MIB_NAME="F5-BIGIP-COMMON-MIB"
T4_BASE_OID="1.3.6.1.4.1.3375.2.4"
T4_TPL_NAME="Template SNMP F5 BIG-IP - Notification"

T5_MIB_NAME="F5-BIGIP-APM-MIB"
T5_BASE_OID="1.3.6.1.4.1.3375.2.5"
T5_TPL_NAME="Template SNMP F5 BIG-IP - APM Compliance"

T6_MIB_NAME="F5-BIGIP-APM-MIB"
T6_BASE_OID="1.3.6.1.4.1.3375.2.6"
T6_TPL_NAME="Template SNMP F5 BIG-IP - APM Base"

T7_MIB_NAME="F5-BIGIP-WAM-MIB"
T7_BASE_OID="1.3.6.1.4.1.3375.2.7"
T7_TPL_NAME="Template SNMP F5 BIG-IP - WAM"

echo ""
echo "Starting..."

echo "Unpacking MIB files"
if [ ! -d ${MIB_DIR} ]; then
    mkdir -p ${MIB_DIR}
fi
if [ -f ${MIB_F5NET} ]; then
    tar xzf ${MIB_F5NET} -C ${MIB_DIR} --strip-components=1
else
    echo "ERROR: Please, download file ${MIB_F5NET} from any F5 BIG-IP device"
    echo ""
    exit 1
fi
if [ -f ${MIB_F5PRIV} ]; then
    tar xzf ${MIB_F5PRIV} -C ${MIB_DIR} --strip-components=1
else
    echo "ERROR: Please, download file ${MIB_F5PRIV} from any F5 BIG-IP device"
    echo ""
    exit 1
fi

echo "Downloading mib2zabbix script"
if [ ! -f ${M2Z_BIN} ]; then
    curl --location --output ${M2Z_BIN} --silent ${M2Z_URL}
    if [ ! -f ${M2Z_BIN} ]; then
        echo "ERROR: Please download file ${M2Z_BIN} from GitHub"
        echo ""
        exit 2
    fi
    chmod +x ${M2Z_BIN}
fi

export MIBS=+${T1_MIB_NAME}:${T2_MIB_NAME}:${T3_MIB_NAME}:${T4_MIB_NAME}:${T5_MIB_NAME}:${T6_MIB_NAME}:${T7_MIB_NAME}

echo "Creating :: ${T1_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T1_TPL_NAME}.xml" --name="${T1_TPL_NAME}" --oid="${T1_BASE_OID}" 2>/dev/null
echo "Creating :: ${T2_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T2_TPL_NAME}.xml" --name="${T2_TPL_NAME}" --oid="${T2_BASE_OID}" 2>/dev/null
echo "Creating :: ${T3_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T3_TPL_NAME}.xml" --name="${T3_TPL_NAME}" --oid="${T3_BASE_OID}" 2>/dev/null
echo "Creating :: ${T4_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T4_TPL_NAME}.xml" --name="${T4_TPL_NAME}" --oid="${T4_BASE_OID}" 2>/dev/null
echo "Creating :: ${T5_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T5_TPL_NAME}.xml" --name="${T5_TPL_NAME}" --oid="${T5_BASE_OID}" 2>/dev/null
echo "Creating :: ${T6_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T6_TPL_NAME}.xml" --name="${T6_TPL_NAME}" --oid="${T6_BASE_OID}" 2>/dev/null
echo "Creating :: ${T7_TPL_NAME}"
${M2Z_BIN} --enable-items --filename="${T7_TPL_NAME}.xml" --name="${T7_TPL_NAME}" --oid="${T7_BASE_OID}" 2>/dev/null

echo "Cleaning up files"
sed -i '' "s/Generated by mib2zabbix/${T1_TPL_NAME} [Base OID: ${T1_BASE_OID}]/" "${T1_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T2_TPL_NAME} [Base OID: ${T2_BASE_OID}]/" "${T2_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T3_TPL_NAME} [Base OID: ${T3_BASE_OID}]/" "${T3_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T4_TPL_NAME} [Base OID: ${T4_BASE_OID}]/" "${T4_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T5_TPL_NAME} [Base OID: ${T5_BASE_OID}]/" "${T5_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T6_TPL_NAME} [Base OID: ${T6_BASE_OID}]/" "${T6_TPL_NAME}.xml"
sed -i '' "s/Generated by mib2zabbix/${T7_TPL_NAME} [Base OID: ${T7_BASE_OID}]/" "${T7_TPL_NAME}.xml"

unset MIBS
echo "Done!"
echo ""
